### Compose

# services:
#   jermuk-city:
#     container_name: jermuk-city
#     image: blackdocs/jermuk-city:649f8b990c6e0ff3a006e6ac69931fa64d6b8952
#     mem_limit: 128m
#     mem_reservation: 68M
#     cpus: 0.2
#     command:
#      - uvicorn
#      - main:app
#      - '--port'
#      - '8888'
#      - '--host'
#      - '0.0.0.0'
#     ports:
#       - 8888:8888



### Swarm Mode

services:
  jermuk-city:
    deploy:
      replicas: 3  
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 68M           
    image: blackdocs/jermuk-city:649f8b990c6e0ff3a006e6ac69931fa64d6b8952
    command:
     - uvicorn
     - main:app
     - '--port'
     - '8888'
     - '--host'
     - '0.0.0.0'
    ports:
      - 8888:8888
    networks:
      - ingress  
networks:
  ingress:
