apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jermuk-city     
  name: jermuk-city
  namespace: webapps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jermuk-city
  template:
    metadata:
      labels:
        app: jermuk-city        
    spec:       
      containers:
      - image: docker.io/blackdocs/jermuk-city:f1a621d66186374d2abc85959242671a8ad0f25c
        name: jermuk-city
        imagePullPolicy: Always                
        resources: 
          requests:
            memory: "30Mi"
            cpu: "5m"
          limits:
            memory: "60Mi"
            cpu: "20m"                  
        ports:
          - containerPort: 8888
            name: http                     
        livenessProbe: 
          httpGet: 
            path: /api/healthz
            port: 8888
          initialDelaySeconds: 5
          periodSeconds: 60
        readinessProbe:
          httpGet:
            path: /api/healthz
            port: 8888
          initialDelaySeconds: 5
          periodSeconds: 60                 
      terminationGracePeriodSeconds: 10

---

apiVersion: v1
kind: Service
metadata:
  name: jermuk-city-svc
  labels:
    app: jermuk-city  
  namespace: webapps
spec:
  selector:
    app: jermuk-city
  ports:
  - name: http
    protocol: TCP
    port: 8888
    targetPort: http

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jermuk-city-ingress
  namespace: webapps
  annotations:
    cert-manager.io/cluster-issuer: production
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: www.jermuk.city
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jermuk-city-svc
            port:
              number: 8888
  tls:
  - hosts:
      - "www.jermuk.city"
    secretName: jermuk-cittls           

# ---

# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: jermuk-city-autoscale
#   namespace: webapps
#   labels:
#     app: jermuk-city
#     env: aws  
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: jermuk-city
#   minReplicas: 2
#   maxReplicas: 3
#   metrics:     
#   - type: Resource
#     resource:
#       name: cpu
#       target:
#         type: Utilization
#         averageUtilization: 90
#   - type: Resource
#     resource:
#       name: memory
#       target:
#         type: Utilization
#         averageUtilization: 90 
