name: Build and Deploy Jermuk-City app
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Image
        run: |
          docker image build -t blackdocs/jermuk-city:${{ github.sha }} ./ 
      - name: Push Image
        run: |
          docker image push   blackdocs/jermuk-city:${{ github.sha }}    
      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.13.2/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq                   
      - name: Replace image tag in values.yaml
        run: |
          yq eval -i '.spec.template.spec.containers[0].tag = "${{ github.sha }}"' ./values.yaml
