name: Build and Deploy Jermuk-City app on Prod
on:
  pull_request:
    branches:
      - main
    types: [closed]  
jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}        
      - name: Build and push
        run: |
          docker build -t blackdocs/jermuk-city:${{ github.sha }} ./ --push      
      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: Blackdocs-Cloud/docker-apps
          ref: main 
          token: ${{ secrets.TOKEN_GITHUB }}          

      - name: Replace image tag 
        run: |
          sed -i "s|docker.io/blackdocs/jermuk-city:[^ ]*|docker.io/blackdocs/jermuk-city:${{ github.sha }}|" docker-compose.yaml
        working-directory: ./

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update image tag to ${GITHUB_SHA}"
          git push origin main   

      - name: Set Slack Message
        id: set-slack-message
        run: echo "::set-output name=message::${{ job.status == 'success' && 'Job Passed :heavy_check_mark:' || 'Job Failed :x:' }}"

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_MSG_AUTHOR: GitHub Bot
          MSG_MINIMAL: true
          SLACK_CHANNEL: alerts-blackdocs
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: ${{ steps.set-slack-message.outputs.message }}
          SLACK_TITLE: Message
          SLACK_USERNAME: GitHub Bot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
