name: Build the Jermuk-City app, test and deploy
on:
  pull_request:
    branches:
      - main
    types: [closed]
jobs:
  node-js-endpoints-tests-prod:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build prod test image
        run: |
          docker build -t blackdocs/jermuk-city:local -f ./bin/Dockerfile ./bin

      - name: Run Tests Prod
        run: |
          bash ./tests/tests.sh

      - name: Report Status For Tests Prod
        if: always()
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          notify_when: "success,failure"
          footer: "<{run_url}|View Run>"
          notification_title: "node-js-endpoints-tests-prod"
          message_format: "{emoji} *{job}* {status_message} on <{commit_url}|{commit_sha}>"
          token: ${{ secrets.repo_token }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

  jermuk-city-ci:
    if: github.event.pull_request.merged == true
    needs: node-js-endpoints-tests-prod
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t blackdocs/jermuk-city:${{ github.sha }} -f ./bin/Dockerfile ./bin --push

      # - name: Push README to Docker Hub
      #   uses: christian-korneck/update-container-description-action@v1
      #   env:
      #     DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
      #     DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
      #   with:
      #     destination_container_repo: blackdocs/jermuk-city
      #     provider: dockerhub
      #     readme_file: './bin/README.md'

      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: Blackdocs-Cloud/live-environments
          ref: main
          token: ${{ secrets.TOKEN_GITHUB }}

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_KEY }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      # - name: Delever to K8S
      #   run: |
      #     sed -i "s|docker.io/blackdocs/jermuk-city:[^ ]*|docker.io/blackdocs/jermuk-city:${{ github.sha }}|" ./saas/jermuk-city/values.yaml
      #   working-directory: ./

      # - name: Sign commit and push changes
      #   run: |
      #     git add .
      #     git config --local user.email "blackdocscloud@gmail.com"
      #     git config --local user.name "blackdocs-bot"
      #     git commit -m "Update image tag to ${GITHUB_SHA}"
      #     git push

      - name: Delever to Docker Compose
        run: |
          sed -i "s|docker.io/blackdocs/jermuk-city:[^ ]*|docker.io/blackdocs/jermuk-city:${{ github.sha }}|" ./docker-live/platform/jermuk-city.yaml
        working-directory: ./

      - name: Sign commit and push changes
        run: |
          git add .
          git config --local user.email "blackdocscloud@gmail.com"
          git config --local user.name "blackdocs-bot"
          git commit -m "Update image tag for jermuk-city"
          git push

      - name: Report Status
        if: always()
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          notify_when: "success,failure"
          footer: "<{run_url}|View Run>"
          notification_title: "jermuk-city CI"
          message_format: "{emoji} *{workflow}* {status_message} on <{commit_url}|{commit_sha}>"
          token: ${{ secrets.repo_token }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

      - name: Docker Compose CD
        working-directory: ./
        run: |
          docker compose -f ./docker-live/platform/jermuk-city.yaml up -d

      - name: Wait for Container to Start
        id: wait
        run: |
          for i in {1..10}; do
            status=$(docker ps -f "ancestor=blackdocs/jermuk-city:${{ github.sha }}" --format "{{.Status}}")
            if [[ "$status" =~ .*Up.* ]]; then
              echo "Container is running"
              echo "::set-output name=container_status::running"
              exit 0
            else
              echo "Container is not running or restarting"
              echo "::set-output name=container_status::not_running"
              exit 1
            fi
            sleep 1
          done

      - name: Report Status
        if: steps.wait.outputs.container_status == 'not_running'
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          notify_when: "failure"
          footer: "<{run_url}|View Run>"
          notification_title: "GitHub CD"
          message_format: |
            {emoji} *jermuk-city* Sync faild. Container not ready
          token: ${{ secrets.repo_token }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

      - name: Report Status
        if: steps.wait.outputs.container_status == 'running'
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          notify_when: "success"
          footer: "<{run_url}|View Run>"
          notification_title: "GitHub CD"
          message_format: |
            {emoji} *jermuk-city* Status Synced
          token: ${{ secrets.repo_token }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
