name: Build and Deploy Jermuk-City app on Prod
on:
  push:
    branches: [ main ]    
jobs:
  build-and-deploy:
    # if: github.event.pull_request.merged == true
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}        
      - name: Build and push
        run: |
          docker build -t blackdocs/jermuk-city:${{ github.sha }} ./ --push      
      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: Blackdocs-Cloud/docker-apps
          ref: main 
          token: ${{ secrets.TOKEN_GITHUB }}          

      - name: Replace image tag 
        run: |
          pwd
          sed -i "s|docker.io/blackdocs/jermuk-city:[^ ]*|docker.io/blackdocs/jermuk-city:${{ github.sha }}|" docker-compose.yaml
        working-directory: ./

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update image tag"
          git push origin main         

      # - name: Replace image tag in values.yaml
      #   run: |
      #     sed -i "s|docker.io/blackdocs/jermuk-city:[^ ]*|docker.io/blackdocs/jermuk-city:${{ github.sha }}|" ./k8s/values.yaml
      # - name: Commit and push changes
      #   run: |
      #     git config user.name "actions"
      #     git config user.email "actions@users.noreply.github.com"
      #     git add .
      #     git commit -m "Update image tag to ${GITHUB_SHA}"
      #     git push          
