name: Build the Jermuk-City app
on:
  pull_request:
    branches:
      - main
    types: [closed]  
jobs:
  jermuk-city-ci:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}        
      - name: Build and push
        run: |
          docker build -t blackdocs/jermuk-city:${{ github.sha }} ./
          docker image push blackdocs/jermuk-city:${{ github.sha }}

      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: Blackdocs-Cloud/live-environments
          ref: main 
          token: ${{ secrets.TOKEN_GITHUB }}
          gpg: ${{ secrets.GPG_KEY_ID }}

      - name: Delever to K8S
        run: |
          sed -i "s|docker.io/blackdocs/jermuk-city:[^ ]*|docker.io/blackdocs/jermuk-city:${{ github.sha }}|" ./saas/jermuk-city/values.yaml
        working-directory: ./

      - name: Commit and push changes
        run: |
          git config --global commit.gpgsign true
          git config --global user.signingkey ${gpg}
          git config --local user.email "blackdocscloud@gmail.com"
          git config --local user.name "blackdocs-bot"
          git add .
          git commit -m "Update image tag to ${GITHUB_SHA}"
          git push origin main   

      - name: Report Status
        if: always()
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          notify_when: "success,failure"
          footer: "<{run_url}|View Run>"
          notification_title: "jermuk-city CI"
          message_format: "{emoji} *{workflow}* {status_message} on <{commit_url}|{commit_sha}>"
          token: ${{ secrets.repo_token }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
