# name: Build and Deploy Jermuk-City app
# on:
#   push:
#     branches: [ dev ]
# jobs:
#   build-and-deploy:
#     runs-on: self-hosted
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3  
#       - name: Log in to Docker Hub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}
#       - name: Build Image
#         run: |
#           docker image build -t blackdocs/jermuk-city:${{ github.sha }} ./ 
#       - name: Push Image
#         run: |
#           docker image push   blackdocs/jermuk-city:${{ github.sha }}                      
#       - name: Replace image tag in values.yaml
#         run: |
#           sed -i "s|docker.io/blackdocs/jermuk-city:[^ ]*|docker.io/blackdocs/jermuk-city:${{ github.sha }}|" ./values.yaml
#       - name: Commit and push changes
#         run: |
#           git config user.name "blackdocs"
#           git config user.email "blackdocs@users.noreply.github.com"
#           git add .
#           git commit -m "Update image tag to ${GITHUB_SHA}"
#           git push           



name: First Cron Job

       # Controls when the workflow will run
on:
  # Triggers the workflow every 5 minutes
  schedule:
    - cron: "*/2 * * * *"

     # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "cron"
  cron:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!