name: Build and Deploy Jermuk-City app
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2          
      - name: Build and push
        uses: docker/build-push-action@v4
        run: |
          docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t blackdocs/jermuk-city:${{ github.sha }} ./ 
          docker image push   blackdocs/jermuk-city:${{ github.sha }}                      
      - name: Replace image tag in values.yaml
        run: |
          sed -i "s|docker.io/blackdocs/jermuk-city:[^ ]*|docker.io/blackdocs/jermuk-city:${{ github.sha }}|" ./values.yaml
      - name: Commit and push changes
        run: |
          git config user.name "actions"
          git config user.email "actions@users.noreply.github.com"
          git add .
          git commit -m "Update image tag to ${GITHUB_SHA}"
          git push           
