name: Bot Workflow
on:
  pull_request:
    types:
      - opened

jobs:
  assign_reviewers:
    runs-on: self-hosted
    steps:
      - name: Assign Reviewer
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.TOKEN_GITHUB }}
          script: |
            const owner = context.payload.repository.owner.login;
            const repo = context.payload.repository.name;
            const prNumber = context.payload.pull_request.number;
            const reviewer = "blackdocs-bot";

            await github.pulls.createReviewRequest({
              owner,
              repo,
              pull_number: prNumber,
              reviewers: [reviewer],
            });

      - name: Auto-Approve and Comment
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.TOKEN_GITHUB }}
          script: |
            const owner = context.payload.repository.owner.login;
            const repo = context.payload.repository.name;
            const prNumber = context.payload.pull_request.number;
            const comment = "This pull request has been automatically approved by the bot.";
            await github.pulls.createReview({
              owner,
              repo,
              pull_number: prNumber,
              event: "APPROVE",
            });
            await github.issues.createComment({
              owner,
              repo,
              issue_number: prNumber,
              body: comment,
            });
